# Generated by Django 5.0.6 on 2024-06-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdetail',
            field=models.CharField(max_length=300, verbose_name='Product Details'),
        ),
    ]
